require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sessions", type: :request do
  
  let(:user_admin) {FactoryBot.create :user_admin}
  let(:user_employee) {FactoryBot.create :user_employee}

  let(:admin_valid_attributes) {
    password: "123456"
    email: user_admin.email
  }

  let(:employee_valid_attributes) {
    password: "123456"
    email: user_employee.email
  }

  let(:invalid_attributes) {
    password: 123456,
    email: 1
  }

  let(:valid_headers) {
    {
      authorization: ,
      content_type: "application/json" 
    }
  }


  describe "POST /login as Admin" do
    context "with valid parameters" do
      it "creates a new Session" do
        expect {
          post "/login",
            params: { user: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Session, :count).by(1)
      end

      it "renders a JSON response with the new session" do
        post sessions_url,
             params: { session: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Session" do
        expect {
          post sessions_url,
               params: { session: invalid_attributes }, as: :json
        }.to change(Session, :count).by(0)
      end

      it "renders a JSON response with errors for the new session" do
        post sessions_url,
             params: { session: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end
end
